<?
$aMenuLinks = Array(
    Array(
        "О компании",
        "/o-kompanii/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Клиентам",
        "/informatsiya/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Портфолио",
        "/portfolio/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Контакты",
        "/kontakty/",
        Array(),
        Array(),
        ""
    )
);
?>